package com.slavikjunior.deorm

import com.slavikjunior.deorm.annotations.Column
import com.slavikjunior.deorm.annotations.Id
import com.slavikjunior.deorm.annotations.Table
import com.slavikjunior.deorm.orm.Entity
import java.sql.Types

@Table(name = "persons")
data class Person(

    @Id(autogenerated = true)
    @Column(name = "id", type = Types.INTEGER, nullable = false)
    val id: Int,

    @Column(name = "firstname", type = Types.VARCHAR, nullable = true)
    val firstName: String? = null,

    @Column(name = "lastname", type = Types.VARCHAR, nullable = true)
    val lastName: String? = null,

    @Column(name = "email", type = Types.VARCHAR, nullable = true)
    val email: String? = null,

    @Column(name = "gender", type = Types.VARCHAR, nullable = true)
    val gender: String? = null,

    @Column(name = "ipaddress", type = Types.VARCHAR, nullable = true)
    val ipAddress: String? = null,

    @Column(name = "country", type = Types.VARCHAR, nullable = true)
    val country: String? = null
) : Entity
